export default {
  DELETE_TRANSACTION: 'DELETE_TRANSACTION',
  ADD_TRANSACTION: 'ADD_TRANSACTION',
  UPDATE_TRANSACTION: 'UPDATE_TRANSACTION',
  EDIT_WALLET: 'EDIT_WALLET',
  TOGGLE_FILTER: 'TOGGLE_FILTER'
}
